### ISSUE TITLE
Parse KBART BookInstance fields and insert in Title JSON

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#91] opened 2019-02-21 13:08 UTC
Corresponding GOKb Issue: https://github.com/openlibraryenvironment/gokb/issues/5

Specific KBART fields for monographs should be inserted in the Title JSON: 

These fields could be inserted without further parsing: 
  * _monograph_volume_ --> `volumeNumber`
  * _first_editor_ --> `firstEditor`
  * _first_author_ --> `firstAuthor`
  * _monograph_edition_ --> `editionDifferentiator`
  * _monograph_edition_ --> `editionStatement`

These fields may need some type checks (as other Dates like coverage dates)
  * _date_monograph_published_print_ --> `dateFirstInPrint` 
  * _date_monograph_published_online_ --> `dateFirstOnline`

These fields may require some additonial functionality / parsing
  * Parsed number value of _monograph_edition_ --> `editionNumber`(_null_ or left blank if no number value exists or more than one number value is found, i.e. "3rd revised and expanded edition" --> "3")
  * _preceding_publication_title_id_  --> should be converted to proper history events for importing them via crossreferencing API.

**Comment by darupp** [comment] 2019-03-06 08:26
Testfiles:

[Ebooks_Kbart.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/580df2094aa9cb1300c82e3a/125516c66e82c728ace21e0d46cd96952c899096a4ebbe51b01fbcd6395428792c07b7692ac7b62aea1223025d0d1fad490b0e12fcf98879f0b569218a5a19f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b98b44c6e83a2de5888d462c53.zip)

**Comment by darupp** [comment] 2019-03-21 17:33
phaeton-qa: Ebook parsing works with none of the Testfiles (Tested Preselect media, Cambridge, Hanser, OUP)
- Tipps are empty
- Parsing Exceptions
- etc.

**Comment by darupp** [comment] 2019-04-04 13:40
Found some errors:
  * *online_identifier* maps to namespace *isbn*. Should be: 
    * *online_identifier* maps to *eisbn*
    * *print_identifier* maps to *isbn*
- 

-

**Comment by philboeselager** [comment] 2019-04-04 14:01
> Found some errors:
> online_identifier maps to namespace isbn. Should be:
> online_identifier maps to eisbn
> print_identifier maps to isbn
> Last part doesn't work (properly?):

@darupp Can you please assert that this is not due to confusing IDs in a connected API? If this is not due to API data, can you please provide the kbart data?

> Parsed number value of monograph_edition --> editionNumber(null or left blank if no number value exists or more than one number value is found, i.e. "3rd revised and expanded edition" --> "3")

Confirmed. This had not been implemented, yet. Can we have a collection of similiar cases to be normalized? It's not that effective if we add normalizing rules one by one. ...but OK, if it has to be like this.

> preceding_publication_title_id --> should be converted to proper history events for importing them via crossreferencing API.

So, we query this `preceding_publication_title_id` at the ZDB API. The GOKb requires the following fields for HistoryEvents:

- eventDate
- participants, each with a role

Can you please specify the ZDB API fields this data has to taken from?

**Comment by hornmo** [comment] 2019-04-04 15:18
> online_identifier maps to namespace isbn. Should be:
        online_identifier maps to eisbn
        print_identifier maps to isbn

@darupp Actually, GOKb currently only knows "isbn", which the _online_identifier_ should be mapped to. There have been no plans to import the ISBNs of parallel print publications that I know of.

**Comment by darupp** [comment] 2019-04-08 13:36
@hornmo Thank you for clarification. As we both agreed, the *print_identifier* should nonetheless imported into the GOKb, as it is given in KBART files like those from Cambridge University Press and helps identifying corresponding print publications. Although, as there is no official e-isbn like there is a e-issn, the print-isbn should be mapped to a new namespace `pisbn` that is not a top level identifier. So the correct mapping would be:
  * *print_identifier* --> `pisbn` (new namespace)
  * *online_identifier* --> `isbn`(as it is realised now)

@philboeselager Please refer to the test files given as zip, especially Cambridge University Press and Elsevier.

Regarding normalization of edition data: As this is a free-text field, we can not give definitive source information. The given example should suffice at the moment. I recommend parsing the string for number values and take this value only if it is the only one. 

Regarding *preceding_publication_title_id*, we don't have the ZDB API, as the ZDB is only for serial information. In this case, the information must solely come from the KBART file itself, where this field refers to an existing *title_id* in the document. As this is quite tricky and refers mainly to problematic half series-half ebook titles, please ignore this task for the moment.

**Comment by croqueGrec09** [comment] 2019-04-08 14:01
Maybe I should point out that any changes on the mapping affect the LAS:eR-side processing of the identifiers, i.e. the preselection of issue entitlements needs to be adapted as well as soon as the mapping changes here because otherwise, we have an identifier mismatch. Cf. LAS:eR-ticket [ERMS-933](https://jira.hbz-nrw.de/browse/ERMS-933)

**Comment by darupp** [comment] 2019-04-08 14:25
@croqueGrec09 We already have the identifier mismatch - this is the reason for reopening the ticket.

**Comment by philboeselager** [comment] 2019-04-16 13:18
@darupp Final part of this issue (editionNumber normalization) is solved in https://github.com/hbz/laser-ygor/commit/34f08afde76a2e88f224880327183c3f2c548c26. I'm going to deploy this tomorrow on DEV.

**Comment by philboeselager** [comment] 2019-04-23 08:27
Deployed on DEV, will be deployed on QA and PROD as soon as I'm told. Closing.

**Closed by philboeselager** 2019-04-23 08:27 UTC
Labels: enhancement, in progress
